# Generated by Django 5.1.4 on 2025-02-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_question_remove_quizmodel_q100_marks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='QuestionModel',
        ),
    ]
