# Generated by Django 5.1.4 on 2025-02-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_remove_questionmodel_level_quizmodel_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='levels',
        ),
    ]
