# Generated by Django 5.1.4 on 2025-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_remove_quizmodel_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='time_remaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
