# Generated by Django 5.1.4 on 2025-02-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_userprogress_time_remaining_userprogress_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='quiz_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
