# Generated by Django 5.1.4 on 2025-02-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_alter_quizmodel_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='current_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='current_question',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='time_remaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='total_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
