# Generated by Django 5.1.4 on 2025-02-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_quizmodel_current_level_quizmodel_current_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
