# Generated by Django 5.1.4 on 2025-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_questionmodel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='status',
            field=models.CharField(blank=True, choices=[('skipped', 'skipped'), ('correct', 'correct'), ('incorrect', 'incorrect'), ('notattempted', 'notattempted')], default='notattempted', max_length=50, null=True),
        ),
    ]
