# Generated by Django 5.1.4 on 2025-02-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0016_badge_quizbadges_delete_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='status',
            field=models.CharField(blank=True, default='notstarted', max_length=100, null=True),
        ),
    ]
