# Generated by Django 5.1.4 on 2025-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_userprofile_top_score_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='status',
            field=models.CharField(blank=True, default='started', max_length=100, null=True),
        ),
    ]
